name=input("whta is your name")
last_name=input("whta is your last_name")
county=input("whta is your country")
color=input("whta is your fovorit color")
car=input("whta is your fovorit car")
print(name)
print(last_name)
print(county)
print(color)
print(car)